sudo: required
services:
  - docker

before_install:
  - docker build -t andresalvarezewe/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true andresalvarezewe/docker-react npm run test
  
